---
title: "CV"
author: "Sam C. Levin"
email: levisc8@gmail.com
output:
  pdf_document:
    keep_tex: yes
    latex_engine: pdflatex
    template: tex_template.tex
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
geometry: margin=1in
github: levisc8
jobtitle: ''
linkcolor: blue
fontawesome: yes
address: German Centre for Integrative Biodiversity, Deutscherplatz 5e, Leipzig, Germany
twitter: SamLevin5
updated: null
urlcolor: blue
---

# Education

*Martin Luther University Halle-Wittenberg*

PhD Biology \hfill 2018-Present

*Martin Luther University Halle-Wittenberg*

MSc Biology \hfill 2016-2017

*Wake Forest University*

BA Biology \hfill 2008-2012

# Work Experience

*Martin Luther University Halle-Wittenberg*

Research Officer \hfill 2018-Present

*Helmholtz-Zentrum für Umweltforschung *

Student Research Assistant \hfill 2017

*German Centre for Integrative Biodiversity*

Student Research Assistant \hfill 2016 - 2018

*University of Missouri-St. Louis*

Field Research Technician \hfill 2015 - 2016	
	
*Washington University in St. Louis*

Field Research Technician \hfill 2014 - 2015

*Student Conservation Association*

National Park Service Southeast EPMT Intern \hfill 2013 - 2014

# Research Interests

**Invasions**: understanding how demography, phylogeny, and functional traits interact to determine who becomes invasive and who remains benign.

**Software Development**: creating open source tools for researchers to efficiently analyze, publish, and share their data.

# Publications

## Journal Articles
$^\ast$ _denotes mentee_

**Levin SC**, Evers S, Pena-Guerrero M, Compagnoni AC, Childs DZ, Knight TM & Salguero-Gomez R (_in prep_). Padrino: An open access database of Integral Projection Models.

**Levin SC**, Compagnoni AC, Salguero-Gomez R, Childs DZ, Evers S & Knight TM (_in prep_). ipmr: Flexibly implement Integral Projection Models in R. 

Bogdan A$^\ast$, **Levin SC**, Salguero-Gomez R & Knight TM. (_in prep_). Demographic analysis of Israeli _Carpobrotus_ populations: management strategies and future directions.

Compagnoni AC, **Levin SC**, Childs DZ, Harpole S, Paniw M, Romer G, _et al._ (_in review_). Short-lived plants have stronger demographic responses to climate. Nature Communications. bioRxiv DOI: 10.1101/2020.06.18.160135

**Levin SC**, Crandall RM, Pokoski TC$^\ast$, Stein C & Knight TM (2020). Phylogenetic and functional distinctiveness explain alien plant population responses to competition. Proceedings of the Royal Society B.  287: 20201070. DOI: 10.1098/rspb.2020.1070

Paniw M, James T, Archer CR, Romer G, **Levin SC**, Compagnoni AC, _et al._ (_in review_). Global analysis reveals complex demographic responses of mammals to climate change.  Journal of Animal Ecology. bioRxiv DOI: 10.1101/2019.12.16.878348

Sandel B, Weigelt P, Kreft H, Keppel G, van der Sande MT, **Levin SC**, Smith S, Craven DC & Knight TM (2019). Current climate, isolation, and history drive global patterns of tree phylogenetic endemism. Global Ecology and Biogeography. DOI: 10.1111/geb.13001

Compagnoni A, Bibian BJ, Ochocki BM, **Levin SC**, Zhu K & Miller TEX (2019). popler: an R package for extraction and synthesis of population time series from the long-term ecological research (LTER) network. Methods in Ecology and Evolution. DOI: 10.1111/2041-210X.13319

**Levin SC**, Crandall RM, Knight TM (2019) Population projection models for 14 alien plant species in the presence and absence of above‐ground competition. Ecology. DOI: 10.1002/ecy.2681 

Carl G, **Levin SC**, Kühn I. (2018) spind: an R Package to Account for Spatial Autocorrelation in the Analysis of Lattice Data. Biodiversity Data Journal.
6: e20760. DOI: 10.3897/BDJ.6.e20760

## Workshops & Invited Talks

**Levin SC**. Invasive plants: research, control, and what you can do to help! Point Reyes National Park, May 2020. (Cancelled due to COVID-19 pandemic).

**Levin SC** & Salguero-Gomez R. Effective, efficient, and safe data collection with UAVs. Oxford University, January 2020.

Salguero-Gomez R, Jones OR, _et al._ A gentle introduction to the COMADRE & COMPADRE databases for demographic analyses. British Ecological Society, Belfast, December 2019.

## Presentations
$^\ast$ _denotes mentee; $^\#$ denotes poster presentations, otherwise oral_


**2018**

**Levin SC**, RM Crandall, TC Pokoski, Stein C, Knight TM. Mechanisms underlying the differential success of alien plant species. Ecological Society of America – New Orleans, USA


**2016**

**Levin SC**, Stein C, Knight TM. Phylogenetic novelty alters the strength of biotic interactions for exotic plant species. NeoBiota 2016 – Vianden, Luxembourg

**Levin SC**, Stein C, Knight TM. Phylogenetic novelty alters the strength of biotic interactions for exotic plant species. iDiv Conference – Leipzig, Germany


**2015**

Poor E$^\ast$,Thompson AH$^\ast$, **Levin SC**, Knight TM. Novel functional traits aid the success of the invasive biennial Carduus nutans. Washington University in St. Louis Undergraduate Research Symposium – St. Louis, MO $^\#$

Workman M$^\ast$, Thompson AH$^\ast$, **Levin SC**, Knight TM. Competitive release may increase the fitness of exotic plants in their novel range. Washington University in St. Louis Undergraduate Research Symposium – St. Louis, MO $^\#$

**2014**

Patterson A$^\ast$, Galluppi CG, **Levin SC**, Maynard EE, Knight TM. How plant species become common: examining the success strategies of native and invasive plants. Washington University in St. Louis Undergraduate Research Symposium – St. Louis, MO $^\#$

Van Horn T$^\ast$, Galluppi CG, **Levin SC**, Knight TM. Examining the enemy release hypothesis in Ozark woody species. Washington University in St. Louis Undergraduate Research Symposium – St. Louis, MO $^\#$

# Software

Maintainer (current) and developer (> v2.0.0) of *spind*. [CRAN](https://cran.r-project.org/web/checks/check_results_spind.html) and [Github](https://github.com/levisc8/spind)

Maintainer and developer of *ipmr*. [Project page](https://levisc8.github.io/ipmr/)

Maintainer and developer of the *Padrino IPM Database* and *Rpadrino*. [Project page](https://github.com/levisc8/RPadrino)

Contributed to development of [popler](https://github.com/AldoCompagnoni/popler), [popdemo](https://github.com/iainmstott/popdemo), [Rcompadre](https://github.com/jonesor/Rcompadre),
and [Rage](https://github.com/jonesor/Rage).

# Languages

Fluent in English and R, proficient with Stan, Git, and C++, and familiar with Python and German.

# Certifications

United States FAA Part 107 UAV Pilot License

United States NPS S212 A Faller

# Mentoring

Ana Bogdan \hfill Babe\c s-Bolyai University, Cluj-Napoca, Romania

Tyler Pokoski \hfill  University of Iowa 2017

Tom Collins \hfill Missouri S&T 2017

Amy Patterson \hfill Washington University in St. Louis 2015

Amibeth Thompson \hfill Illinois College 2014

Sami Hunkler \hfill University of California, Berkeley 2017

Thomas Van Horn \hfill Washington University in St. Louis 2018

Sarah Link \hfill Eureka High School 2015

Brenda Alvarado \hfill Francis Howell North 2015

Matilda Workman \hfill Kirkwood High School 2017

Elizabeth Poor \hfill Clayton High School 2017

# Service

Reviewer for rOpenSci, BMC Ecology, Annals of Botany, and Plant Ecology

# Referees

**Dr. Tiffany Knight**

Martin Luther University, Helmholtz-Zentrum für Umweltforschung, German Centre for Integrative Biodiversity

<tiffany.knight@idiv.de>

**Dr. Roberto Salguero-Gomez**

Oxford University Department of Zoology

<rob.salguero@zoo.ox.ac.uk>
