---
title: "Sam C. Levin"
author: "Pragerstr. 119, 04103 Leipzig, Germany"
email: levisc8@gmail.com
output:
  word_document
urlcolor: blue
---

# Work Experience

**Martin Luther University Halle-Wittenberg**

*Research Officer* 

02/2018-Present 

26h/week

\$34,000/Year

  + Designed, implemented, documented, and maintained an R package, `ipmr`, for creating Integral Projection Models in the R programming language. This software allows users to implement mathematical models of the dynamics of structured populations using a broad range of underlying statistical models.
  
  + Designed, implemented, documented, and maintained a database, `PADRINO`, to re-build published Integral Projection Models to address synthetic questions in ecology and evolutionary biology. `PADRINO` includes models of plants, animals, fish, corals, and insects. Users can re-construct, project population dynamics, and extend these models using functionality provided through `RPadrino` (an R package to interface with the database), and `ipmr`.
  
  + Designed and carried out data collection for _Carpobrotus_ species across 6 countries and 23 field sites in their native and invaded ranges using novel, drone based methodology. 
  
  + Created high resolution orthomosaics (2-4 mm/pixel) for each _Carpobrotus_ species population using Pix4DMapper. 
  
  + Extracted size, survival, growth, and reproduction information from each orthomosaic using QGIS. 
  
  + Analyzed drone data using R, Stan, and C++ programming languages to connect environmental covariates to population dynamics for inference on areas at risk for future invasion under different climate scenarios. All analyses were version controlled with Git.
  
  + Published papers in peer-reviewed journals and presented results at conferences (See "Publications" and "Presentations" sections below).
  
  + Participated in _sApropos_ and _Phylogenetic Endemism in Trees_ working groups.
  
  + Mentored BSc. and MSc. level students (See "Mentoring" section below).

**Helmholtz-Zentrum für Umweltforschung**

*Student Research Assistant*

05/2017

10h/week

\$10,560/Year

  + Implemented the `spind` R package. This package provides methods for dealing with spatially autocorrelated data using Generalized Estimating Equations and Wavelet Revised Models. It also provides methods for model selection, diagnostics, and visualization.
  
  + Published papers in peer-reviewed journals (See "Publications" section below).

**Martin Luther University Halle-Wittenberg**

*Student Research Assistant*

07/2016 - 01/2018 

20h/week

\$10,560/Year

  + Created matrix population models and integral projection models from demographic data for 14 non-native plant species for inference on population dynamics in the presence and absence of competition. 
  
  + Used regression modeling to link per-capita growth rates in the presence and absence of competition to phylogenetic and functional dissimilarity from the local community. 
  
  + Published results in peer reviewed journals and presented results at conferences (See "Publications" and "Presentations" sections below).

**University of Missouri-St. Louis**

*Field Research Technician*

11/2015 - 03/2016	

37.5h/week

\$33,000/Year

  + Collected demographic data on 14 non-native plant species from Washington University in St. Louis Tyson Research Center and Shaw Nature Reserve.
  
  + Collected functional trait data for approximately 120 plant species from Tyson Research Center.
  
  + Created matrix population models and integral projection models from demographic data for 14 non-native plant species for inference on population dynamics in the presence and absence of competition. 
  
  + Mentored BSc. level students (See "Mentoring" section below).
	
**Washington University in St. Louis**

*Field Research Technician*

04/2014 - 10/2015 

37.5h/week

\$33,000/Year

  + Collected demographic data on 14 non-native plant species from Washington University in St. Louis Tyson Research Center and Shaw Nature Reserve.
  
  + Collected functional trait data for approximately 120 plant species from Tyson Research Center.
  
  + Created matrix population models and integral projection models from demographic data for 14 non-native plant species for inference on population dynamics in the presence and absence of competition. 
  
  + Managed day to day field sampling operations for a 3 year, $500,000 NSF grant. 
  
  + Supervised 4-7 undergraduate research assistants during field data collection.
  
  + Mentored BSc. level students (See "Mentoring" section below).

**Student Conservation Association**

*National Park Service Southeast EPMT Intern*

09/2013 - 04/2014 

40h/week

\$10,000/Year

  + Managed invasive plant species in National Parks in the Southeastern United States using mechanical and chemical control methods.
  
  + Maintained equipment including, but not limited to, chainsaws, backpack sprayers, and ATVs.

# Education

*Martin Luther University Halle-Wittenberg*

PhD Biology \hfill 02/2018-Present

*Martin Luther University Halle-Wittenberg*

MSc Biology \hfill 04/2016-12/2017

*Wake Forest University*

BA Biology \hfill 08/2008-05/2012

# Publications

## Peer-reviewed Publications
$^\ast$ _denotes mentee_

Keppel G, Craven D, Weigelt P, Smith SA, van der Sande MT, Sandel B, **Levin SC**, Kreft H & Knight TM (2021). Synthesizing tree biodiversity data to understand global patterns and processes of vegetation. Journal of Vegetation Science. DOI: 10.1111/jvs.13021

**Levin SC**, Childs DZ, Compagnoni AC, Evers S$^\ast$, Knight TM & Salguero-Gomez R (_in review_ at _Methods in Ecology and Evolution_). ipmr: Flexibly implement Integral Projection Models in R. 

Bogdan A$^\ast$, **Levin SC**, Salguero-Gomez R & Knight TM. (2021). Demographic analysis of an Israeli _Carpobrotus_ population. Plos One. DOI: 10.1371/journal.pone.0250879.

Paniw M, James T, Archer CR, Romer G, **Levin SC**, Compagnoni AC, _et al._ (2021). Global analysis reveals complex demographic responses of mammals to climate change. Journal of Animal Ecology. DOI: 10.1111/1365-2656.13467

Compagnoni AC, **Levin SC**, Childs DZ, Harpole S, Paniw M, Romer G, _et al._ (2021). Short-lived plants have stronger demographic responses to climate. Nature Communications. Nature Communications. DOI: 10.1038/s41467-021-21977-9

**Levin SC**, Crandall RM, Pokoski TC$^\ast$, Stein C & Knight TM (2020). Phylogenetic and functional distinctiveness explain alien plant population responses to competition. Proceedings of the Royal Society B. DOI: 10.1098/rspb.2020.1070

Sandel B, Weigelt P, Kreft H, Keppel G, van der Sande MT, **Levin SC**, Smith S, Craven DC & Knight TM (2019). Current climate, isolation, and history drive global patterns of tree phylogenetic endemism. Global Ecology and Biogeography. DOI: 10.1111/geb.13001

Compagnoni A, Bibian BJ, Ochocki BM, **Levin SC**, Zhu K & Miller TEX (2019). popler: an R package for extraction and synthesis of population time series from the long-term ecological research (LTER) network. Methods in Ecology and Evolution. DOI: 10.1111/2041-210X.13319

**Levin SC**, Crandall RM, Knight TM (2019) Population projection models for 14 alien plant species in the presence and absence of above‐ground competition. Ecology. DOI: 10.1002/ecy.2681 

Carl G, **Levin SC**, Kühn I. (2018) spind: an R Package to Account for Spatial Autocorrelation in the Analysis of Lattice Data. Biodiversity Data Journal. DOI: 10.3897/BDJ.6.e20760

## Workshops & Invited Talks

**Levin SC**, Childs DZ, Compagnoni AC, Evers S, Knight TM & Salguero-Gomez R. `ipmr`: An R Package for Easy and Flexible Construction and Interpretation of Integral Projection Models. Ecological Society of America, Long Beach, August 2021.

**Levin SC**. Invasive plants: research, control, and what you can do to help. Point Reyes National Park, May 2020. (Canceled due to COVID-19 pandemic).

**Levin SC** & Salguero-Gomez R. Effective, efficient, and safe data collection with UAVs. Oxford University, January 2020.

Salguero-Gomez R, Jones OR, _et al._ A  gentle introduction to the COMADRE & COMPADRE databases for demographic analyses. British Ecological Society, Belfast, December 2019.

## Conference Presentations
$^\ast$ _denotes mentee; $^\#$ denotes poster presentations, otherwise oral_

**2020**

Salguero-Gomez R,Che-Castaldo JP, Jones O, Caswell H, Ezard T, Hernandez-Yanez H, Hodgson D, Knight TM, **Levin SC**, Stott I, Thomas C, Vaupel J. (2020) The next generation of demographic databases: Building and delivering a distributed network for user contributions and engagement. Ecological Society of America

**2018**

**Levin SC**, RM Crandall, TC Pokoski, Stein C, Knight TM. Mechanisms underlying the differential success of alien plant species. Ecological Society of America – New Orleans, USA


**2016**

**Levin SC**, Stein C, Knight TM. Phylogenetic novelty alters the strength of biotic interactions for exotic plant species. NeoBiota 2016 – Vianden, Luxembourg

**Levin SC**, Stein C, Knight TM. Phylogenetic novelty alters the strength of biotic interactions for exotic plant species. iDiv Conference – Leipzig, Germany


**2015**

Poor E$^\ast$,Thompson AH$^\ast$, **Levin SC**, Knight TM. Novel functional traits aid the success of the invasive biennial Carduus nutans. Washington University in St. Louis Undergraduate Research Symposium – St. Louis, MO $^\#$

Workman M$^\ast$, Thompson AH$^\ast$, **Levin SC**, Knight TM. Competitive release may increase the fitness of exotic plants in their novel range. Washington University in St. Louis Undergraduate Research Symposium – St. Louis, MO $^\#$

**2014**

Patterson A$^\ast$, Galluppi CG, **Levin SC**, Maynard EE, Knight TM. How plant species become common: examining the success strategies of native and invasive plants. Washington University in St. Louis Undergraduate Research Symposium – St. Louis, MO $^\#$

Van Horn T$^\ast$, Galluppi CG, **Levin SC**, Knight TM. Examining the enemy release hypothesis in Ozark woody species. Washington University in St. Louis Undergraduate Research Symposium – St. Louis, MO $^\#$

# Software

Maintainer (current) and developer (> v2.0.0) of *spind*. [Project page](https://github.com/levisc8/spind) and  [CRAN](https://cran.r-project.org/package=spind)

Maintainer and developer of *ipmr*. [Project page](https://levisc8.github.io/ipmr/) and [CRAN](https://cran.r-project.org/package=ipmr)

Maintainer and developer of the *Padrino IPM Database* and *Rpadrino*. [Project page](https://levisc8.github.io/Padrino/).

Contributed to development of [popler](https://github.com/AldoCompagnoni/popler), [bRacatus](https://github.com/EduardoArle/bRacatus), [plotbiomes](https://github.com/valentinitnelav/plotbiomes), [popdemo](https://github.com/iainmstott/popdemo), [Rcompadre](https://github.com/jonesor/Rcompadre),
and [Rage](https://github.com/jonesor/Rage).

# Languages

Fluent in English and R, proficient with Stan, Git, and C++, and familiar with Python and German.

# Certifications

United States FAA Part 107 UAV Pilot License

United States NPS S212 A-Faller

# Mentoring

Sanne Evers \hfill Helmholtz-Zentrum für Umweltforschung 

Ana Bogdan \hfill Babe\c s-Bolyai University, Cluj-Napoca, Romania

Tyler Pokoski \hfill  University of Iowa 2017

Tom Collins \hfill Missouri S&T 2017

Amy Patterson \hfill Washington University in St. Louis 2015

Amibeth Thompson \hfill Illinois College 2014

Sami Hunkler \hfill University of California, Berkeley 2017

Thomas Van Horn \hfill Washington University in St. Louis 2018

Sarah Link \hfill Eureka High School 2015

Brenda Alvarado \hfill Francis Howell North 2015

Matilda Workman \hfill Kirkwood High School 2017

Elizabeth Poor \hfill Clayton High School 2017

# Service

Reviewer for rOpenSci, BMC Ecology, Annals of Botany, and Plant Ecology.

# Referees

**Dr. Tiffany Knight**

Martin Luther University, Helmholtz-Zentrum für Umweltforschung, German Centre for Integrative Biodiversity

<tiffany.knight@idiv.de>

**Dr. Roberto Salguero-Gomez**

Oxford University Department of Zoology

<rob.salguero@zoo.ox.ac.uk>
